### ISSUE TITLE
Failed to start encoder: Function not implemented

### ISSUE THREAD

**Issue by Willy19921992** [hgaiser/moonshine#10]
Some Nvidia GPUs (like the GTX 16 series and older) do not support B-Frames, which results in the following error when trying to stream with moonshine:

```
INFO  moonshine::session::stream::video::encoder] Using codec with name 'hevc_nvenc'.
[hevc_nvenc @ 0x747de9243680] Multiple reference frames are not supported by the device
[hevc_nvenc @ 0x747de9243680] Provided device doesn't support required NVENC features
ERROR moonshine::session::stream::video::encoder] Failed to start encoder: Function not implemented
```

I believe this error is caused by the following line:
https://github.com/hgaiser/moonshine/blob/66fc9a76ed1010220156590d834e350e68743c5a/src/session/stream/video/encoder.rs#L120

It could be nice to enable users to slightly tweak this values in the config.toml file to avoid certain incompatibilities with NVENC capable GPUs.

My system has a GTX 1650 Max-Q running Arch Linux (I also tried patching NvFBC with: https://github.com/keylase/nvidia-patch)

**Comment by Willy19921992** [comment]
Yes, in my case setting that value to 0 does fix it:

```
INFO  moonshine::session::stream::video::encoder] Using codec with name 'hevc_nvenc'.
INFO  moonshine::session::stream::video::capture] Started frame capture.
```

I'm not entirely sure of what reference frames are either, but I found this: https://obsproject.com/forum/threads/what-is-the-b-frames-nvenc.55145/
I was also having trouble with OBS screen recording while using NVENC (using VA-API was fine though), and changing the max b-frames setting to 0 fixed it, so I thought something similar was happening here.

**Comment by hgaiser** [comment]
Do you want to submit a PR to set it to 0? I tested it today and it worked
fine for me as well :). Otherwise I'll do it later.

**Comment by Willy19921992** [comment]
Yes, I can do it, if you give me a couple of minutes to fork the repo.

**Comment by hgaiser** [comment]
Thanks :) I'll release a new version soon. In the meantime you can use moonshine-git or from source, since you've compiled it already ;)

**Comment by hgaiser** [comment]
The latest version includes this change, thanks :+1:

**Comment by Willy19921992** [comment]
Nice! I'll try it out later to see if I can find any other issues.
