### ISSUE TITLE
Black screen "No video recieved from host"

### ISSUE THREAD

**Issue by zoobporsor** [hgaiser/moonshine#13]
I'm unable to get Moonshine to function. On the client after trying to connect through Moonlight, it gives a black screen with a weird broken white border and after awhile "No video recieved from host". I'm using Arch Linux on the host with a GTX 2080ti. I followed the directions on the main page but maybe I missed something. What could cause this?

**Comment by zoobporsor** [comment]
Is it because I'm using KDE Plasma on Wayland? Does this project not support Wayland at the moment?

**Comment by hgaiser** [comment]
On the host side you need to use X, unfortunately. It's a limitation in the
frame capture library from Nvidia.

**Comment by hgaiser** [comment]
> EDIT: Well, the same thing happens on X11 session, So I guess its not that
> 
> I am using the latest nvidia-open drivers on arch, everything is stock and default. Do I need to do some custom Nvidia patched driver thing to get the encoders to work properly on Linux or something?

A patched driver shouldn't be necessary, but it's worth a try. I wasn't using the nvidia-open drivers, but I think I did at some point and it worked as well.

Are there any error messages on the host side?

**Comment by hgaiser** [comment]
Closing, let me know if this is still an issue (feel free to reopen in that case too).

**Comment by shagr4th** [comment]
Thanks for the detailed reply, I've already looked at the code and compiled everything with your patches, everything seems ok, but the pipewiresrc video pipeline won't switch to a playing state, thus leaving the moonlight screen black (along with the "no video stream" error). I'll keep digging later, but it's likely a driver issue

**Comment by hgaiser** [comment]
Good luck :) you can also hit me up on the Moonlight discord server, there's even a dedicated channel for Moonshine there.
